name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      CI_ROLE:
        required: true
      SSH_KEY_GITHUB_ACTIONS:
        required: true

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.work-dir }}
    steps:
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.CI_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Uncomment the following lines if you need to set up Python and other dependencies
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' # install the python version needed

      # - name: Install Python Packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pyhcl

      # - name: Install Dependencies
      #   run: |
      #     apt-get update && apt-get install -y wget
      #     wget https://github.com/tfsec/tfsec/releases/download/v0.58.5/tfsec-linux-amd64
      #     chmod +x tfsec-linux-amd64
      #     mv tfsec-linux-amd64 /usr/local/bin/tfsec

      - name: Set up SSH and Initialize Terraform
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY_GITHUB_ACTIONS }}"
          terraform init

      - name: Format Terraform Files
        run: terraform fmt

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
         

      - name: Show Terraform Plan
        run: terraform show -json ./tfplan > tfplan.json

      - name: Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          framework: terraform
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v2
        with:   
            name: terraform-plan
            path: tfplan
        
